### ISSUE TITLE
Extra memory

### ISSUE THREAD

**Issue by okovtun** [Presstomsk/Dynamic_Memory#1]
Здравствуйте Рома! Функции для двумерных массивов используют много памяти, и при больших массивах могут падать.
Использование памяти нужно оптимизировать.

**Comment by Presstomsk** [comment]
Ваше письмо поступило в обработку. С Вами обязательно свяжутся.

**Comment by Presstomsk** [comment]
Оптимизировал. Убрал дублирующие функции. https://github.com/Presstomsk/Dynamic_Memory/tree/dynamic_templated_2

**Comment by Presstomsk** [comment]
# https://github.com/Presstomsk/Dynamic_Memory/tree/dynamic_templated_2

**Comment by okovtun** [comment]
Не, все равно немного не то, посмотрите здесь: https://github.com/okovtun/BD_011/blob/master/DynamicMemory/DynamicMemory/main.cpp

**Comment by Presstomsk** [comment]
#2
